### PR TITLE
Add React Support

### PR DESCRIPTION
**Pull request by thomas-huston-zocdoc**
@Andrew-Hagedorn-ZocDoc 

Changes
--
- Add support for compiling JSX files in Bundler.

### CODE REVIEW

**Comment by thomas-huston-zocdoc** [comment]
Still working out a few kinks.

**Comment by thomas-huston-zocdoc** [comment]
@Andrew-Hagedorn-ZocDoc okay should be good to go.

**Comment by thomas-huston-zocdoc** [comment]
@Andrew-Hagedorn-ZocDoc thoughts on this?

**Comment by Andrew-Hagedorn-ZocDoc** [comment]
:+1: 

We should hold off on using it on the core site until we are committed to making this the sole technology we use.

**Comment by thomas-huston-zocdoc** [comment]
There's no particular plan for where we want to use this, but the point is to unblock people from trying it out. I think ideally we'll do some internal pages with it to get a feel for React.

**Pull request merged**
